# Generated by Django 4.2.20 on 2025-03-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
